<p class="has-text-align-center">MOSTER &amp; 墨魂创想</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">这是展示简约内容的网页                       It is a web page showing simple content.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">比如文章，社群消息                For example, articles, community news.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"contentJustification":"center"} -->
<div class="wp-block-buttons is-content-justification-center"><!-- wp:button {"borderRadius":50,"backgroundColor":"black","textColor":"white","width":100} -->
<div class="wp-block-button has-custom-width wp-block-button__width-100"><a class="wp-block-button__link has-white-color has-black-background-color has-text-color has-background" href="http://z915088581.github.io/moster" style="border-radius:50px" target="_blank" rel="noreferrer noopener">进入官网</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->
